version: "3"
services:
  postgres:
    container_name: database_postgres
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: root
      POSTGRES_DB: my_database
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - local-network

  redis_server:
    image: redis:alpine
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - local-network

networks:
  local-network:
    external:
      name: local-network
